/**
 * Hacker House Goa 2026 — Generative Identity DNA & Composition Systems Engine v2.0
 */

export const EDITIONS = [
  'AFTER HOURS EDITION',
  'SIGNAL EDITION',
  'COASTAL EDITION',
  'FIELD EDITION',
  'ARCHIVE EDITION',
  'NIGHT EDITION',
  'SPECIAL EDITION',
]

export const COMPOSITION_SYSTEMS_12 = [
  '01 — ARCHITECTURAL GRID',
  '02 — EDITORIAL COVER',
  '03 — FIELD CREDENTIAL',
  '04 — SIGNAL MAP',
  '05 — ARCHIVE DOCUMENT',
  '06 — POSTCARD',
  '07 — NIGHT TRANSMISSION',
  '08 — MANIFESTO',
  '09 — SYSTEM DIAGNOSTIC',
  '10 — FESTIVAL POSTER',
  '11 — DEEP FIELD',
  '12 — COLLAGE',
]

export const WORLDS = {
  goan: {
    id: 'goan',
    name: 'Goan Golden Hour',
    subtitle: 'Golden Hour on the Beach',
    desc: 'Vintage Goa travel postcard with golden sunset tones, palms, Portuguese tiles, & coastal warmth.',
    mode: 'golden',
    code: 'GH',
    palette: {
      primaryBg: '#073B2A',
      secondaryBg: '#0B5D3B',
      sunColor: '#FFD21C',
      accentColor: '#C94B36',
      creamColor: '#FFF1C7',
    },
    variants: [
      'golden-beach-palms',
      'sunset-shack-sea',
      'portuguese-villa-foliage',
      'coastal-horizon-postcard',
      'beach-festival-atmosphere',
    ],
    motif: '🏖️',
    stampCode: 'GOA POSTAL • GOLDEN HOUR',
  },
  afterdark: {
    id: 'afterdark',
    name: 'Goa After Dark',
    subtitle: '2 AM in the Hacker House',
    desc: 'Deep green night sky, tropical moon, twinkling stars, neon shack lights & late-night focus.',
    mode: 'night',
    code: 'AD',
    palette: {
      primaryBg: '#071A18',
      secondaryBg: '#073B2A',
      sunColor: '#FFF1C7',
      accentColor: '#F02B72',
      creamColor: '#FFF1C7',
    },
    variants: [
      'moon-beach-shack',
      'night-ocean-foliage',
      'hacker-house-residency',
      'neon-coastal-road',
      'late-night-festival',
    ],
    motif: '🌙',
    stampCode: 'GOA NIGHT RESIDENCY • 02:47 AM',
  },
  degen: {
    id: 'degen',
    name: 'Goa Degen Party',
    subtitle: 'On-Chain Maximalism',
    desc: 'Goa beach party × crypto builder culture with neon signage, surf graphics, & kinetic energy.',
    mode: 'degen',
    code: 'DG',
    palette: {
      primaryBg: '#071A18',
      secondaryBg: '#F02B72',
      sunColor: '#FFD21C',
      accentColor: '#F02B72',
      creamColor: '#FFF1C7',
    },
    variants: [
      'beach-party',
      'neon-tropical-night',
      'festival-signage-surf',
      'crypto-builder-party',
      'kinetic-goa-nightlife',
    ],
    motif: '⚡',
    stampCode: 'DEGEN PASS • ON-CHAIN // 2026',
  },
}

export const ARCHETYPES = {
  ARCHITECT: {
    id: 'ARCHITECT',
    name: 'Architect',
    code: 'ARC',
    desc: 'Systems thinker. Designs for scale.',
    symbol: '📐',
    trait: 'Structured Geometry & Grid Lines',
    layoutStyle: 'structured',
  },
  HACKER: {
    id: 'HACKER',
    name: 'Hacker',
    code: 'HAK',
    desc: 'Breaks things to build better.',
    symbol: '⚡',
    trait: 'Technical Microdetails & Scan Marks',
    layoutStyle: 'technical',
  },
  EXPLORER: {
    id: 'EXPLORER',
    name: 'Explorer',
    code: 'EXP',
    desc: 'Maps unknown territory.',
    symbol: '🗺️',
    trait: 'Postcard Compass & Coordinate Motifs',
    layoutStyle: 'postcard',
  },
  DEGEN: {
    id: 'DEGEN',
    name: 'Degen',
    code: 'DGN',
    desc: 'Full send. No regrets.',
    symbol: '🔥',
    trait: 'Kinetic Party Graphics & High Contrast',
    layoutStyle: 'kinetic',
  },
  VISIONARY: {
    id: 'VISIONARY',
    name: 'Visionary',
    code: 'VIS',
    desc: "Sees what isn't there yet.",
    symbol: '👁️',
    trait: 'Dreamlike Sky Glow & Halo Motifs',
    layoutStyle: 'dreamlike',
  },
  CHAOS_ENGINEER: {
    id: 'CHAOS_ENGINEER',
    name: 'Chaos Engineer',
    code: 'CHS',
    desc: 'Thrives in disorder.',
    symbol: '🌀',
    trait: 'Asymmetric Screenprint Offsets',
    layoutStyle: 'asymmetric',
  },
  RESEARCHER: {
    id: 'RESEARCHER',
    name: 'Researcher',
    code: 'RSC',
    desc: 'Goes deep. Surfaces insights.',
    symbol: '🔬',
    trait: 'Annotated Archive Stamp Details',
    layoutStyle: 'archive',
  },
  MAKER: {
    id: 'MAKER',
    name: 'Maker',
    code: 'MKR',
    desc: 'Ships fast. Iterates faster.',
    symbol: '🛠️',
    trait: 'Industrial Serial Marks & Badges',
    layoutStyle: 'production',
  },
}
